version: "3.9"

services:
  postgres:
    image: postgres:13.2
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    networks:
      - local-keycloak

  keycloak:
    image: jboss/keycloak:13.0.0
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: app
      DB_USER: app
      DB_PASSWORD: app
    ports:
      - "28080:8080"
    depends_on:
      - postgres
    networks:
      - local-keycloak
    # volumes:
    #   - ./keycloak:/app

networks:
  local-keycloak:
