version: "3.9" # Adjust the version if needed

services:
  keycloak_unoptimized:
    image: quay.io/keycloak/keycloak:latest
    ports:
      - "8008:8080"
    environment:
      KEYCLOAK_ADMIN: main
      KEYCLOAK_ADMIN_PASSWORD: main
    # volumes:
    #   - /keycloak:/opt/keycloak/data/import
    command: start-dev --import-realm
